spring.application.name=oauth2-simple-demo

spring.security.oauth2.client.registration.auth0.client-id=6dtEE2PLSrukvxbc4yeiK6K0vNqC9q5t
spring.security.oauth2.client.registration.auth0.client-secret=jU50V3LIqsY2hIKDQ-tY4Iz1xFOh5wTBmHuNtTWcQWroqaoLSJMDbZY3lyiwxYJg
spring.security.oauth2.client.registration.auth0.scope=openid, email, profile
spring.security.oauth2.client.provider.auth0.issuer-uri=https://dev-irmc4lc0ud0pjug3.us.auth0.com/

logging.level.root=ERROR
logging.level.org.springframework.web=ERROR
logging.level.org.springframework.security=TRACE
logging.level.com.auth0=TRACE
logging.level.biz.lci=TRACE